### ISSUE TITLE
mtime resolution on Windows

### ISSUE THREAD

**Issue by julian-r** [benhoyt/scandir#63]
It seems just seems like something is going wrong on py 3.4 win10-x64. The resolution is not matching with os.stat, it is truncating everything but seconds:

Py 3.4:

```
>>> a = list(scandir.scandir('c:\\'))  
>>> os.stat('c:\\bootmgr').st_mtime
1446189514.1278422
>>> a[1].stat().st_mtime
1446189514
```

Py 3.5: build in

```
>>> a = list(os.scandir('c:\\'))
>>> a[1].stat().st_mtime
1446189514.1278422
```

**Comment by arguile-** [comment]
The same is occuring on linux using Python 2.7 despite `static int _stat_float_times = 1`.

**Comment by arguile-** [comment]
Lookin in _scandir.c, the `stat_result_fields` are defined as:

```
    {"st_atime",   "integer time of last access"},
    {"st_mtime",   "integer time of last modification"},
    {"st_ctime",   "integer time of last change"},
    {"st_atime",   "time of last access"},
    {"st_mtime",   "time of last modification"},
    {"st_ctime",   "time of last change"},
    {"st_atime_ns",   "time of last access in nanoseconds"},
    {"st_mtime_ns",   "time of last modification in nanoseconds"},
    {"st_ctime_ns",   "time of last change in nanoseconds"},
```

Notice the double definition of `st_?time` for the integer then float names. The integer definitions are being accessed instead of the float values even though `fill_time()` is adding the floats for platforms with nanosecond time resolution.

What is the expected behaviour here? I'd expect it to be consistent with `os.stat()` for the given Python version (and will make a PR to that effect if that's the decision).

**Comment by benhoyt** [comment]
@arguile- Thanks. Yes, this looks like a bug. Would love it if you could provide a PR with a fix (including tests). In the CPython 3.5 codebase `stat_result_fields` has NULL for those names rather than redefining them (which I think is the problem, you're right). See https://github.com/python/cpython/blob/3.5/Modules/posixmodule.c#L1750-L1753

```c
static PyStructSequence_Field stat_result_fields[] = {
    {"st_mode",    "protection bits"},
    {"st_ino",     "inode"},
    {"st_dev",     "device"},
    {"st_nlink",   "number of hard links"},
    {"st_uid",     "user ID of owner"},
    {"st_gid",     "group ID of owner"},
    {"st_size",    "total size, in bytes"},
    /* The NULL is replaced with PyStructSequence_UnnamedField later. */
    {NULL,   "integer time of last access"},
    {NULL,   "integer time of last modification"},
    {NULL,   "integer time of last change"},
    {"st_atime",   "time of last access"},
    {"st_mtime",   "time of last modification"},
    {"st_ctime",   "time of last change"},
    {"st_atime_ns",   "time of last access in nanoseconds"},
    {"st_mtime_ns",   "time of last modification in nanoseconds"},
    {"st_ctime_ns",   "time of last change in nanoseconds"},
    ...
```

**Comment by benhoyt** [comment]
And then later on:

```c
        stat_result_desc.fields[7].name = PyStructSequence_UnnamedField;
        stat_result_desc.fields[8].name = PyStructSequence_UnnamedField;
        stat_result_desc.fields[9].name = PyStructSequence_UnnamedField;
```

**Comment by benhoyt** [comment]
Excellent, thanks for this. I've tested on my current setup and it works well. I've merged your PR and will produce a release shortly.

**Comment by rene0** [comment]
On FreeBSD 12 (64-bit) with Python 2.7.12 installed two tests still fail, no patches are in use:

======================================================================
FAIL: test_stat (test_scandir.TestScandirC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/rene/freebsd/ports/head/sysutils/py-scandir/work/scandir-1.4/test/test_scandir.py", line 137, in test_stat
    self.assertEqual(os_stat.st_ctime, scandir_stat.st_ctime)
AssertionError: 1478968940.873746 != 1478968940

----------------------------------------------------------------------
Ran 33 tests in 0.028s

FAILED (failures=1, skipped=3)
*** Error code 1

Same for st_mtime on line 136.

Is this because scandir thinks that FreeBSD has no nanosecond precision for stat(2) ?

**Comment by benhoyt** [comment]
Thanks, @rene0 -- I don't have access to or experience with *BSD, but here's what's probably the relevant code in `_scandir.c`. Are you interested in digging into why one of the relevant #define's aren't defined.

```
#if defined(HAVE_STAT_TV_NSEC)
    ansec = st->st_atim.tv_nsec;
    mnsec = st->st_mtim.tv_nsec;
    cnsec = st->st_ctim.tv_nsec;
#elif defined(HAVE_STAT_TV_NSEC2)
    ansec = st->st_atimespec.tv_nsec;
    mnsec = st->st_mtimespec.tv_nsec;
    cnsec = st->st_ctimespec.tv_nsec;
#elif defined(HAVE_STAT_NSEC)
    ansec = st->st_atime_nsec;
    mnsec = st->st_mtime_nsec;
    cnsec = st->st_ctime_nsec;
#else
    ansec = mnsec = cnsec = 0;
#endif
```

**Comment by rene0** [comment]
If I add a #warning after each if #defined() I see that HAVE_STAT_TV_NSEC is defined, so the three variables should be set but they do not  seem to propagate?

Defined here, found with grepping in /usr/src (FreeBSD source code), /usr/include (FreeBSD base headers) and /usr/local/include (third-party headers) in /usr/local/include/python2.7/pyconfig.h :

> /* Define if you have struct stat.st_mtim.tv_nsec */
> #define HAVE_STAT_TV_NSEC 1
>
> /* Define if you have struct stat.st_mtimensec */ <-- typo in struct name?
> #define HAVE_STAT_TV_NSEC2 1

And if we look in /usr/include/sys/stat.h : 
> struct stat {
> ...
> struct timespec st_mtim; <-- activates HAVE_STAT_TV_NSEC
> ...
> }
> ...
> #define st_mtimespec            st_mtim <-- activates HAVE_STAT_TV_NSEC2
> ...

And finally struct timespec itself is declared in /usr/include/sys/_timespec.h : 
> struct timespec {
>       time_t  tv_sec;         /* seconds */
>       long    tv_nsec;        /* and nanoseconds */
>};

However, if I assign 22, 33 and 44 to respectively ansec, mnsec, and cnsec in the first #if, the test still fails (as expected) but scandir_stat.st_mtime still has no fractional part.

Perhaps sometimes goes wrong in fill_time(), can I easily test that?
